# Generated by Django 5.2.4 on 2025-08-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_id', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('name', models.CharField(max_length=255, verbose_name='Adı Soyadı')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Sigorta Şirketi')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Poliçe Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(default='64AD748', max_length=20, verbose_name='Plaka Numarası')),
                ('license_number', models.CharField(default='B5658E', max_length=50, verbose_name='Ruhsat Numarası')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance_app.customer', verbose_name='Müşteri')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancecompany', verbose_name='Sigorta Şirketi')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.policytype', verbose_name='Poliçe Tipi')),
            ],
        ),
    ]
