# Generated by Django 5.2.4 on 2025-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyadi', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='police_adet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='policy',
            name='referans',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='license_number',
            field=models.CharField(max_length=50, verbose_name='Ruhsat Numarası'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='plate_number',
            field=models.CharField(max_length=20, verbose_name='Plaka Numarası'),
        ),
    ]
