# Generated by Django 5.2.4 on 2025-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_referans_policy_aciklama_policy_police_adet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='police_adet',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='referans',
        ),
        migrations.AddField(
            model_name='referans',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referans',
            name='police_adet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referans',
            name='referans',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
